trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - release/*
      - hotfix/*
      - feature/*
  
pr:
  branches:
    include:
    - bug-fix/*
    - feature/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/.net/Splinter.sln'
  nanoTypesNugetProject: 'src/.net/Splinter.Nuget.NanoTypes.Default/Splinter.Nuget.NanoTypes.Default.csproj'
  nanoInstancesNugetProject: 'src/.net/Splinter.Nuget.NanoInstances.Default/Splinter.Nuget.NanoInstances.Default.csproj'
  buildConfiguration: 'Release'
  ngBuildConfiguration: '--prod'
  coreVersion: "6.x"
  major: 1
  minor: 2
  revision: 0
  buildNumber: $[counter(variables['major'], 0)]
  ${{ if or(contains(variables['Build.SourceBranch'], 'feature/'), contains(variables['Build.SourceBranch'], 'bug-fix/'))  }}:
    releaseType: '-alpha'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    releaseType: '-beta'
  ${{ if contains(variables['Build.SourceBranch'], 'release/') }}:
    releaseType: '-rc'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    releaseType: ''
  versionNumber: $[format('{0}.{1}.{2}.{3}{4}', variables['major'], variables['minor'], variables['revision'], variables['buildNumber'], variables['releaseType'])]
  
name: $(versionNumber)
jobs:
- job: Build
  steps:
  
  - task: UseDotNet@2
    displayName: Install .NET Core 6.0 Runtime
    inputs:      
      version: '$(coreVersion)'
        
  - task: DotNetCoreCLI@2
    displayName: Restore .NET Core Solution
    inputs:
      command: restore
      projects: '$(solution)'
        
  - task: DotNetCoreCLI@2
    displayName: Build .NET Core Solution
    inputs:
      command: build
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration) --no-restore  /p:Version=$(versionNumber)'


  - task: DotNetCoreCLI@2
    displayName: Test .NET Core Solution
    inputs:
      command: test
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore --no-build --filter TestCategory!=Integration'  
      
  - task: DotNetCoreCLI@2
    displayName: Package Nano Types NuGet library
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    inputs:
      command: pack
      packagesToPack: '$(nanoTypesNugetProject)'
      packDestination: '$(Build.ArtifactStagingDirectory)'
      noBuild: true
      includeSymbols: true
      versioningScheme: byEnvVar
      versionEnvVar: 'versionNumber'
      
  - task: DotNetCoreCLI@2
    displayName: Package Nano Instances NuGet library
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    inputs:
      command: pack
      packagesToPack: '$(nanoInstancesNugetProject)'
      packDestination: '$(Build.ArtifactStagingDirectory)'
      noBuild: true
      includeSymbols: true
      versioningScheme: byEnvVar
      versionEnvVar: 'versionNumber'      

  - task: NuGetCommand@2
    displayName: Publish Splinter Nano Types Nuget to nuget.org
    continueOnError: true
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/Splinter.Agents.NanoTypes.Default.$(versionNumber).nupkg;'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget.org'
      allowPackageConflicts: true
      includeSymbols: true
      
  - task: NuGetCommand@2
    displayName: Publish Splinter Nano Instances Nuget to nuget.org
    continueOnError: true
    condition: and(succeededOrFailed(), eq(variables['Build.SourceBranchName'], 'master'))
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/Splinter.Agents.NanoInstances.Default.$(versionNumber).nupkg;'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget.org'
      allowPackageConflicts: true
      includeSymbols: true      